apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-medium-java
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: swaggerapi/petstore:1.0.7
